spring:
  application:
    name: sboot-atomico-mcp-serve

  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/mcpserve
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  mcp:
    server:
      name: account-mcp-server
      version: 1.0.0
      type: SYNC
      stdio:
        enabled: false
      sse-message-endpoint: /mcp/message
logging:
  level:
    org.springframework.ai: DEBUG

server:
  port: 8060